### PR TITLE
Fix/wrong elbow name and forearm sensors ref link

### PR DESCRIPTION
**Pull request by nunoguedelha**
This change fixes issue https://github.com/robotology-playground/icub-model-generator/issues/21.

### CODE REVIEW

**Comment by nunoguedelha** [comment]
@traversaro

**Comment by traversaro** [comment]
Tests are failing with : 
~~~
[ERROR] Specified sensor type imu of imu is not recognised, parsing failed.icub-model-test error: base_link test performed correctly 

icub-model-test error: sole are parallel test performed correctly 

[ERROR] Specified sensor type imu of imu is not recognised, parsing failed.[ERROR] Specified sensor type imu of imu is not recognised, parsing failed.[ERROR] ModelLoader :: loadModelFromFile : Error in parsing sensors from URDF.
~~~
Perhaps we need to make the sensor-parser in iDynTree more tolerant to not recognized sensor types.

**Comment by traversaro** [comment]
Build restarted after https://github.com/robotology/idyntree/issues/208 .

**Comment by traversaro** [comment]
Tests are passing, merging.

**Pull request merged**
