### PR TITLE
Integrate new workflow

### PR DESCRIPTION
**Pull request by traversaro**
Depends on https://github.com/robotology/simmechanics-to-urdf/pull/20 . 

Integrate the new workflow with CMake, and automatically generate models for the first three robots that we support: 
* `iCubGenova02` 
* `iCubDarmstadt01`
* `iCubGenova05`

### CODE REVIEW

**Comment by traversaro** [comment]
@DanielePucci the latest generated models (commited in https://github.com/robotology-playground/icub-model-generator/pull/10/commits/714050f92d0f8c1e04c8e0f3e3f7f75fa70059e9) should work fine.

**Comment by DanielePucci** [comment]
👍

**Comment by traversaro** [comment]
For solving https://github.com/robotology-playground/icub-model-generator/issues/12 we should integrate the v1 generation workflow (i.e. make sure that it compiles) and then merge this branch.

**Comment by traversaro** [comment]
With the latest modification, the new branch is able to generate fully working URDF models. We are still missing Gazebo models generation, but those need to be revised because the model at https://github.com/robotology/icub-gazebo have been modified extensivly (i.e. the eyes/hand has been added) so we will need to revise that part anyway.

**Pull request merged**
