### PR TITLE
[WIP] Debug travis

### PR DESCRIPTION
**Pull request by nunoguedelha**
- Added catkin dependency in the apt-get command

### CODE REVIEW

**Comment by fiorisi** [comment]
Can we merge this PR?

**Comment by nunoguedelha** [comment]
@fiorisi , No, actually this PR was only for debugging purpose, since we couldn't login directly to a Travis system to debug the Travis builds. But there is a new procedure that we have to try (https://github.com/loc2/loc2.github.io/issues/9). I'll close this PR as soon as this new procedure is tested and proven efficient.

**Comment by traversaro** [comment]
I think we can close this PR nevertheless, and open a new test PR if you need to debug Travis another time.

**Comment by nunoguedelha** [comment]
yes sure :). And let's hope it won't even be necessary.

**Comment by fiorisi** [comment]
I closed the PR, let me know if we need to re-open it again.

**Pull request closed without merging**
