### PR TITLE
Update damping in simulation models

### PR DESCRIPTION
**Pull request by fiorisi**
* Updated the damping value of the simulation models
* Removed the box for feet collision from the non-simulation models

### CODE REVIEW

**Comment by nunoguedelha** [comment]
@traversaro , for some reason, YCM is not building on Travis, I have no idea why. Would you have an idea?

**Comment by traversaro** [comment]
I had the same problem on Jenkins. I will check this evening!

**Comment by nunoguedelha** [comment]
Now the build on the merge commit on master is failing: https://travis-ci.org/robotology-playground/icub-model-generator/builds/327474219.
this prevents the automatic commit to be done on the repo `icub-models`. The failure is due to the command "sudo apt-get update" failing, which is due to the GPG key expired on the `MongoDB` repo. It is apparently a recurrent issue. It is now tracked in https://github.com/travis-ci/travis-ci/issues/9037.

**Comment by nunoguedelha** [comment]
We could try this workaround https://github.com/marmarek/qubes-builder/commit/f7fa3696adc21508b426a17f8a8536649f146f97 which removes the `MongoDB` repo. `MongoDB` is a document database (https://www.mongodb.com/what-is-mongodb).
@traversaro do we need this repo? Would it break something if we remove it? I'll give a try..

**Comment by nunoguedelha** [comment]
The support team released an express fix. It's now working. the build on the merged commit completed successfully.

**Pull request merged**
