### PR TITLE
Properly install mesh and conf folders

### PR DESCRIPTION
**Pull request by diegoferigo**

### CODE REVIEW

**Comment by traversaro** [comment]
I suspect that the `conf` directory will need to be renamed to something else in the future, but for the time being this is ok. Waiting for @nunoguedelha review before merging.

**Comment by diegoferigo** [comment]
Ok let's wait @traversaro (should I have the rights to merge on this repo?)

**Comment by traversaro** [comment]
Admin permission granted. 
Regarding the `POST_BUILD` option (see https://cmake.org/cmake/help/v3.2/command/add_custom_command.html , CMake 2.4 is quite old!) it should not change anything because `copy-models-to-icub-models` is a custom target added with an empty add_custom_target ( https://cmake.org/cmake/help/v3.2/command/add_custom_target.html ) so there is actually no "Build" phase.

**Comment by nunoguedelha** [comment]
> Regarding the POST_BUILD option (... CMake 2.4 is quite old!)

Absolutely true @traversaro. Now, looking at the documentation of the latest Cmake version (https://cmake.org/cmake/help/v3.9/command/add_custom_command.html), we get for `POST_BUILD` the action "Run after all other rules within the target have been executed".

> copy-models-to-icub-models is a custom target added with an empty add_custom_target ( https://cmake.org/cmake/help/v3.2/command/add_custom_target.html ) so there is actually no "Build" phase.

True if you first generate the models, and then copy them ("building" target `copy-models-to-icub-models`). But `add_dependencies(copy-models-to-icub-models generate-models)` allows you to build directly `copy-models-to-icub-models` in one command, triggering the generation of the URDF models. In this case I think it is useful to set the option `POST_BUILD`

**Comment by traversaro** [comment]
@nunoguedelha totally correct, I overlooked the `add_dependencies` part!

**Pull request merged**
